# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import calc_pb2 as calc__pb2


class CalculatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.add = channel.unary_unary(
                '/calc.Calculator/add',
                request_serializer=calc__pb2.InNumbers.SerializeToString,
                response_deserializer=calc__pb2.OutNumber.FromString,
                )
        self.mult = channel.unary_unary(
                '/calc.Calculator/mult',
                request_serializer=calc__pb2.InNumbers.SerializeToString,
                response_deserializer=calc__pb2.OutNumber.FromString,
                )
        self.pow = channel.unary_unary(
                '/calc.Calculator/pow',
                request_serializer=calc__pb2.InNumbers.SerializeToString,
                response_deserializer=calc__pb2.OutNumber.FromString,
                )


class CalculatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def add(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def mult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def pow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalculatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'add': grpc.unary_unary_rpc_method_handler(
                    servicer.add,
                    request_deserializer=calc__pb2.InNumbers.FromString,
                    response_serializer=calc__pb2.OutNumber.SerializeToString,
            ),
            'mult': grpc.unary_unary_rpc_method_handler(
                    servicer.mult,
                    request_deserializer=calc__pb2.InNumbers.FromString,
                    response_serializer=calc__pb2.OutNumber.SerializeToString,
            ),
            'pow': grpc.unary_unary_rpc_method_handler(
                    servicer.pow,
                    request_deserializer=calc__pb2.InNumbers.FromString,
                    response_serializer=calc__pb2.OutNumber.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calc.Calculator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Calculator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def add(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calc.Calculator/add',
            calc__pb2.InNumbers.SerializeToString,
            calc__pb2.OutNumber.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def mult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calc.Calculator/mult',
            calc__pb2.InNumbers.SerializeToString,
            calc__pb2.OutNumber.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def pow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calc.Calculator/pow',
            calc__pb2.InNumbers.SerializeToString,
            calc__pb2.OutNumber.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
