INSERT INTO medico (bi,nome,morada) VALUES ('hE325','Kristen Petty','3073 Lobortis Rd.');
INSERT INTO medico (bi,nome,morada) VALUES ('pD890','Tucker Benjamin','Ap #575-1765 Tincidunt Rd.');
INSERT INTO medico (bi,nome,morada) VALUES ('k1403','Malik Thompson','7951 Rutrum Avenue');
INSERT INTO medico (bi,nome,morada) VALUES ('g5595','Xanthus Valencia','4027 Malesuada Rd.');
INSERT INTO medico (bi,nome,morada) VALUES ('mD448','Shelley Booth','564-3071 Est. St.');
INSERT INTO medico (bi,nome,morada) VALUES ('nDE34','Sean Cole','Ap #597-9440 Adipiscing St.');
INSERT INTO medico (bi,nome,morada) VALUES ('d8D90','Maggie Guerra','Ap #953-3977 Interdum. Rd.');
INSERT INTO medico (bi,nome,morada) VALUES ('p0D54','Freya Snow','3380 Ac, St.');
INSERT INTO medico (bi,nome,morada) VALUES ('pA876','Aristotle Gamble','4634 Facilisis, St.');
INSERT INTO medico (bi,nome,morada) VALUES ('fD153','Lavinia Conrad','Ap #372-7898 Ut Avenue');
INSERT INTO medico (bi,nome,morada) VALUES ('jC117','Eaton Walker','Ap #628-6281 Turpis Av.');
INSERT INTO medico (bi,nome,morada) VALUES ('gAF88','Regan Ewing','538-9791 Auctor Rd.');
INSERT INTO medico (bi,nome,morada) VALUES ('yA394','Kimberley Palmer','8429 Velit Street');
INSERT INTO medico (bi,nome,morada) VALUES ('c1C19','Gage Phelps','574-3784 Rutrum Rd.');
INSERT INTO medico (bi,nome,morada) VALUES ('g5A19','Adele Newton','286-8654 Elit, Avenue');
INSERT INTO medico (bi,nome,morada) VALUES ('tC940','Harriet Forbes','P.O. Box 363, 4458 Turpis Rd.');
INSERT INTO medico (bi,nome,morada) VALUES ('l0093','Kiara Gibbs','7763 Nullam Av.');
INSERT INTO medico (bi,nome,morada) VALUES ('wF789','Ray Anderson','3807 At Rd.');
INSERT INTO medico (bi,nome,morada) VALUES ('bDC30','Darryl Hall','3326 Auctor Ave');
INSERT INTO medico (bi,nome,morada) VALUES ('sCB20','Felicia Burgess','736 Fusce St.');
INSERT INTO medico (bi,nome,morada) VALUES ('pC037','Rudyard Soto','4260 Et St.');
INSERT INTO medico (bi,nome,morada) VALUES ('z2615','Patricia Sullivan','Ap #175-7920 Arcu St.');
INSERT INTO medico (bi,nome,morada) VALUES ('w2192','Christian Vaughan','Ap #382-526 Eros Ave');
INSERT INTO medico (bi,nome,morada) VALUES ('n2E03','Quinn Ingram','4852 Mauris. Avenue');
INSERT INTO medico (bi,nome,morada) VALUES ('nA587','Whitney Townsend','P.O. Box 651, 7515 Ultrices Av.');
INSERT INTO medico (bi,nome,morada) VALUES ('jCA65','Griffin Wade','P.O. Box 536, 8964 Ante. Av.');
INSERT INTO medico (bi,nome,morada) VALUES ('l4561','Desirae Casey','Ap #549-6271 Parturient Avenue');
INSERT INTO medico (bi,nome,morada) VALUES ('m6224','Pandora Alvarez','Ap #466-995 Tellus Rd.');
INSERT INTO medico (bi,nome,morada) VALUES ('c5A94','Camille Roth','P.O. Box 523, 6110 Risus. Road');
INSERT INTO medico (bi,nome,morada) VALUES ('l9431','Raya Watts','P.O. Box 892, 6710 Diam St.');
INSERT INTO medico (bi,nome,morada) VALUES ('wE735','Solomon Hyde','P.O. Box 579, 6108 Donec St.');
INSERT INTO medico (bi,nome,morada) VALUES ('j5674','Stephen Freeman','Ap #310-6443 Nunc Rd.');
INSERT INTO medico (bi,nome,morada) VALUES ('l2452','Buckminster Donovan','Ap #514-6162 Non St.');
INSERT INTO medico (bi,nome,morada) VALUES ('pE370','Rahim Hammond','694 Vivamus St.');
INSERT INTO medico (bi,nome,morada) VALUES ('qA551','Xyla Powell','603 Erat Road');
INSERT INTO medico (bi,nome,morada) VALUES ('y2312','Constance Sweet','690-855 Posuere Av.');
INSERT INTO medico (bi,nome,morada) VALUES ('gBD60','Winifred Harrison','P.O. Box 554, 654 Tempor Rd.');
INSERT INTO medico (bi,nome,morada) VALUES ('g7C98','Noelle Bates','P.O. Box 967, 1769 Eget, Avenue');
INSERT INTO medico (bi,nome,morada) VALUES ('mDE23','Knox Griffith','P.O. Box 239, 3528 Rutrum, Street');
INSERT INTO medico (bi,nome,morada) VALUES ('f8775','Yuri Rojas','Ap #818-3079 Mattis. Rd.');
INSERT INTO medico (bi,nome,morada) VALUES ('jD110','Amela Gray','846-2185 Nulla Avenue');
INSERT INTO medico (bi,nome,morada) VALUES ('w3C04','Timothy Holmes','3310 Imperdiet Rd.');
INSERT INTO medico (bi,nome,morada) VALUES ('cE183','Nathan Munoz','Ap #767-1864 Viverra. Avenue');
INSERT INTO medico (bi,nome,morada) VALUES ('qC816','Reuben Webster','P.O. Box 683, 7069 Et, Rd.');
INSERT INTO medico (bi,nome,morada) VALUES ('p8210','Anjolie Johnson','Ap #936-3218 Neque. Avenue');
INSERT INTO medico (bi,nome,morada) VALUES ('h9F20','Nyssa Howell','8006 Quam. Rd.');
INSERT INTO medico (bi,nome,morada) VALUES ('fCC04','Teagan Pierce','320-6233 Nunc Rd.');
INSERT INTO medico (bi,nome,morada) VALUES ('j4132','Naomi Francis','5508 Non Avenue');
INSERT INTO medico (bi,nome,morada) VALUES ('hF466','Quincy Oneal','282-416 Nulla. Avenue');
INSERT INTO medico (bi,nome,morada) VALUES ('x1C95','Amelia Daugherty','Ap #359-7254 Nulla Road');
INSERT INTO medico (bi,nome,morada) VALUES ('vF039','Ulla Tate','P.O. Box 909, 5513 Aliquam Avenue');
INSERT INTO medico (bi,nome,morada) VALUES ('y9F80','Christopher Turner','Ap #919-8765 Mi Street');
INSERT INTO medico (bi,nome,morada) VALUES ('s2106','Gil Rodgers','7822 Varius Street');
INSERT INTO medico (bi,nome,morada) VALUES ('jBA46','Sandra Hardin','1773 Vel, Ave');
INSERT INTO medico (bi,nome,morada) VALUES ('r0559','Michelle Crosby','181 Facilisis. Rd.');
INSERT INTO medico (bi,nome,morada) VALUES ('qFA97','Benedict Forbes','Ap #381-5554 Sapien, Av.');
INSERT INTO medico (bi,nome,morada) VALUES ('cF641','Buckminster Holcomb','683-3188 Arcu. Ave');
INSERT INTO medico (bi,nome,morada) VALUES ('l5838','Ivor Franklin','4566 Tellus. Road');
INSERT INTO medico (bi,nome,morada) VALUES ('g1C79','Gail Briggs','P.O. Box 892, 8686 Suspendisse Road');
INSERT INTO medico (bi,nome,morada) VALUES ('f0447','Portia Blevins','660-4895 Aliquam St.');
INSERT INTO medico (bi,nome,morada) VALUES ('h1C75','Quentin Cote','5054 Urna. Av.');
INSERT INTO medico (bi,nome,morada) VALUES ('v4927','Mariko Chapman','P.O. Box 879, 2306 Eros Av.');
INSERT INTO medico (bi,nome,morada) VALUES ('z9408','Neville Ortiz','954 Arcu Avenue');
INSERT INTO medico (bi,nome,morada) VALUES ('t4D99','Naida Sutton','P.O. Box 174, 7599 Mauris. Rd.');
INSERT INTO medico (bi,nome,morada) VALUES ('xBE45','Bianca Frost','507 Scelerisque St.');
INSERT INTO medico (bi,nome,morada) VALUES ('fBB80','Nora Mckay','9806 Lorem Road');
INSERT INTO medico (bi,nome,morada) VALUES ('kDA23','Cadman Holt','221-8243 Eleifend. Avenue');
INSERT INTO medico (bi,nome,morada) VALUES ('vAE03','Abigail Ashley','1836 Nunc St.');
INSERT INTO medico (bi,nome,morada) VALUES ('zCE59','Fuller Hubbard','629-9653 Dolor Ave');
INSERT INTO medico (bi,nome,morada) VALUES ('rB606','Octavius Clark','3879 Interdum. Rd.');
INSERT INTO medico (bi,nome,morada) VALUES ('p3656','Kelly Grant','P.O. Box 744, 1114 Felis Rd.');
INSERT INTO medico (bi,nome,morada) VALUES ('d0807','Shelley Mendez','210-5265 Turpis. Rd.');
INSERT INTO medico (bi,nome,morada) VALUES ('zDB43','Kato Sanford','P.O. Box 537, 3958 Ipsum. Ave');
INSERT INTO medico (bi,nome,morada) VALUES ('tD320','Vaughan Gordon','1579 Dolor. Avenue');
INSERT INTO medico (bi,nome,morada) VALUES ('tCC42','Branden Mcbride','516-5314 Nec St.');
INSERT INTO medico (bi,nome,morada) VALUES ('tF567','Kermit Cameron','3374 Magna. Street');
INSERT INTO medico (bi,nome,morada) VALUES ('pF481','Daquan Rollins','Ap #127-4377 Conubia Avenue');
INSERT INTO medico (bi,nome,morada) VALUES ('v2052','Indira Avila','P.O. Box 196, 8366 Nec St.');
INSERT INTO medico (bi,nome,morada) VALUES ('tAF89','Wesley Cohen','398-698 Eu Avenue');
INSERT INTO medico (bi,nome,morada) VALUES ('s1566','Ginger Brady','P.O. Box 129, 7418 Tempus Rd.');
INSERT INTO medico (bi,nome,morada) VALUES ('p0870','Lunea Mann','Ap #696-1920 Fermentum Street');
INSERT INTO medico (bi,nome,morada) VALUES ('nDA42','Xandra Kaufman','6490 Nec, St.');
INSERT INTO medico (bi,nome,morada) VALUES ('v2B26','Shannon Ellison','921-1211 Sem Road');
INSERT INTO medico (bi,nome,morada) VALUES ('l8A27','Clare Spencer','Ap #643-1227 Mauris Ave');
INSERT INTO medico (bi,nome,morada) VALUES ('b9996','Hyacinth Montoya','687-2621 Pellentesque Rd.');
INSERT INTO medico (bi,nome,morada) VALUES ('gEA62','Lars Phelps','857-8881 Iaculis St.');
INSERT INTO medico (bi,nome,morada) VALUES ('qBD24','Jamalia Hatfield','P.O. Box 475, 6910 Vestibulum, St.');
INSERT INTO medico (bi,nome,morada) VALUES ('l0104','Price Duncan','2709 Magna. Ave');
INSERT INTO medico (bi,nome,morada) VALUES ('y7F55','Harper Hebert','P.O. Box 407, 2729 Egestas Avenue');
INSERT INTO medico (bi,nome,morada) VALUES ('pCA98','Melissa Hampton','664-918 Magnis St.');
INSERT INTO medico (bi,nome,morada) VALUES ('x6550','Denton Rivers','5605 Laoreet Ave');
INSERT INTO medico (bi,nome,morada) VALUES ('k2F81','Aubrey Cleveland','662 Eu Rd.');
INSERT INTO medico (bi,nome,morada) VALUES ('qDB93','Rhona Hansen','P.O. Box 412, 2310 Integer Av.');
INSERT INTO medico (bi,nome,morada) VALUES ('t6754','Danielle Fleming','933-4373 Sed Rd.');
INSERT INTO medico (bi,nome,morada) VALUES ('p0996','Lester Andrews','Ap #219-7407 Elit, Road');
INSERT INTO medico (bi,nome,morada) VALUES ('p8B47','Amela Morrison','P.O. Box 139, 8695 Blandit Rd.');
INSERT INTO medico (bi,nome,morada) VALUES ('k5D97','Portia Harrington','P.O. Box 371, 3754 Nullam Ave');
INSERT INTO medico (bi,nome,morada) VALUES ('q5800','Montana Prince','114-9579 Tincidunt St.');
INSERT INTO medico (bi,nome,morada) VALUES ('nA797','Karina Sampson','Ap #205-6292 Purus Av.');
INSERT INTO medico (bi,nome,morada) VALUES ('l8F15','Dillon Lester','P.O. Box 200, 6449 A, Rd.');
