INSERT INTO doenca  (ref,designacao) VALUES (00, 'Cólera');
INSERT INTO doenca  (ref,designacao) VALUES (01, 'Febres Tifóide e Paratifóide');
INSERT INTO doenca  (ref,designacao) VALUES (02, 'Outras Infecções Por Salmonella');
INSERT INTO doenca  (ref,designacao) VALUES (03, 'Shiguelose');
INSERT INTO doenca  (ref,designacao) VALUES (04, 'Outras Infecções Intestinais Bacterianas');
INSERT INTO doenca  (ref,designacao) VALUES (05, 'Outras Intoxicações Alimentares Bacterianas, Não Classificadas em Outra Parte');
INSERT INTO doenca  (ref,designacao) VALUES (06, 'Amebíase');
INSERT INTO doenca  (ref,designacao) VALUES (07, 'Outras Doenças Intestinais Por Protozoários');
INSERT INTO doenca  (ref,designacao) VALUES (08, 'Infecções Intestinais Virais, Outras e as Não Especificadas');
INSERT INTO doenca  (ref,designacao) VALUES (09, 'Diarréia e Gastroenterite de Origem Infecciosa Presumível');
INSERT INTO doenca  (ref,designacao) VALUES (15, 'Tuberculose Respiratória, Com Confirmação Bacteriológica e Histológica');
INSERT INTO doenca  (ref,designacao) VALUES (16, 'Tuberculose Das Vias Respiratórias, Sem Confirmação Bacteriológica ou Histológica');
INSERT INTO doenca  (ref,designacao) VALUES (17, 'Tuberculose do Sistema Nervoso');
INSERT INTO doenca  (ref,designacao) VALUES (18, 'Tuberculose de Outros Órgãos');
INSERT INTO doenca  (ref,designacao) VALUES (19, 'Tuberculose Miliar');
INSERT INTO doenca  (ref,designacao) VALUES (20, 'Peste');
INSERT INTO doenca  (ref,designacao) VALUES (21, 'Tularemia');
INSERT INTO doenca  (ref,designacao) VALUES (22, 'Carbúnculo');
INSERT INTO doenca  (ref,designacao) VALUES (23, 'Brucelose');
INSERT INTO doenca  (ref,designacao) VALUES (24, 'Mormo e Melioidose');
INSERT INTO doenca  (ref,designacao) VALUES (25, 'Febres Transmitidas Por Mordedura de Rato');
INSERT INTO doenca  (ref,designacao) VALUES (26, 'Erisipelóide');
INSERT INTO doenca  (ref,designacao) VALUES (27, 'Leptospirose');
INSERT INTO doenca  (ref,designacao) VALUES (28, 'Outras Doenças Bacterianas Zoonóticas Não Classificadas em Outra Parte');
INSERT INTO doenca  (ref,designacao) VALUES (30, 'Hanseníase (doença de Hansen) (lepra)');
INSERT INTO doenca  (ref,designacao) VALUES (31, 'Infecções Devidas a Outras Micobactérias');
INSERT INTO doenca  (ref,designacao) VALUES (32, 'Listeriose (listeríase)');
INSERT INTO doenca  (ref,designacao) VALUES (33, 'Tétano do Recém-nascido (neonatal)');
INSERT INTO doenca  (ref,designacao) VALUES (34, 'Tétano Obstétrico');
INSERT INTO doenca  (ref,designacao) VALUES (35, 'Outros Tipos de Tétano');
INSERT INTO doenca  (ref,designacao) VALUES (36, 'Difteria');
INSERT INTO doenca  (ref,designacao) VALUES (37, 'Coqueluche');
INSERT INTO doenca  (ref,designacao) VALUES (38, 'Escarlatina');
INSERT INTO doenca  (ref,designacao) VALUES (39, 'Infecção Meningogócica');
INSERT INTO doenca  (ref,designacao) VALUES (40, 'Septicemia Estreptocócica');
INSERT INTO doenca  (ref,designacao) VALUES (41, 'Outras Septicemias');
INSERT INTO doenca  (ref,designacao) VALUES (42, 'Actinomicose');
INSERT INTO doenca  (ref,designacao) VALUES (43, 'Nocardiose');
INSERT INTO doenca  (ref,designacao) VALUES (44, 'Bartonelose');
INSERT INTO doenca  (ref,designacao) VALUES (46, 'Erisipela');
INSERT INTO doenca  (ref,designacao) VALUES (48, 'Outras Doenças Bacterianas Não Classificadas em Outra Parte');
INSERT INTO doenca  (ref,designacao) VALUES (49, 'Infecção Bacteriana de Localização Não Especificada');
INSERT INTO doenca  (ref,designacao) VALUES (50, 'Sífilis Congênita');
INSERT INTO doenca  (ref,designacao) VALUES (51, 'Sífilis Precoce');
INSERT INTO doenca  (ref,designacao) VALUES (52, 'Sífilis Tardia');
INSERT INTO doenca  (ref,designacao) VALUES (53, 'Outras Formas e as Não Especificadas da Sífilis');
INSERT INTO doenca  (ref,designacao) VALUES (54, 'Infecção Gonocócica');
INSERT INTO doenca  (ref,designacao) VALUES (55, 'Linfogranuloma (venéreo) Por Clamídia');
INSERT INTO doenca  (ref,designacao) VALUES (56, 'Outras Infecções Causadas Por Clamídias Transmitidas Por Via Sexual');
INSERT INTO doenca  (ref,designacao) VALUES (57, 'Cancro Mole');
INSERT INTO doenca  (ref,designacao) VALUES (58, 'Granuloma Inguinal');
INSERT INTO doenca  (ref,designacao) VALUES (59, 'Tricomoníase');
INSERT INTO doenca  (ref,designacao) VALUES (60, 'Infecções Anogenitais Pelo Vírus do Herpes (herpes Simples)');
INSERT INTO doenca  (ref,designacao) VALUES (63, 'Outras Doenças de Transmissão Predominantemente Sexual, Não Classificadas em Outra Parte');
INSERT INTO doenca  (ref,designacao) VALUES (64, 'Doenças Sexualmente Transmitidas, Não Especificadas');
INSERT INTO doenca  (ref,designacao) VALUES (65, 'Sífilis Não-venérea');
INSERT INTO doenca  (ref,designacao) VALUES (66, 'Bouba');
INSERT INTO doenca  (ref,designacao) VALUES (67, 'Pinta (carate)');
INSERT INTO doenca  (ref,designacao) VALUES (68, 'Febres Recorrentes (Borrelioses)');
INSERT INTO doenca  (ref,designacao) VALUES (69, 'Outras Infecções Por Espiroquetas');
INSERT INTO doenca  (ref,designacao) VALUES (70, 'Infecções Causadas Por Clamídia Psittaci');
INSERT INTO doenca  (ref,designacao) VALUES (71, 'Tracoma');
INSERT INTO doenca  (ref,designacao) VALUES (74, 'Outras Doenças Causadas Por Clamídias');
INSERT INTO doenca  (ref,designacao) VALUES (75, 'Tifo Exantemático');
INSERT INTO doenca  (ref,designacao) VALUES (77, 'Febre Maculosa (rickettsioses Transmitidas Por Carrapatos)');
INSERT INTO doenca  (ref,designacao) VALUES (78, 'Febre Q');
INSERT INTO doenca  (ref,designacao) VALUES (79, 'Outras Rickettsioses');
INSERT INTO doenca  (ref,designacao) VALUES (80, 'Poliomielite Aguda');
INSERT INTO doenca  (ref,designacao) VALUES (81, 'Infecções Por Vírus Atípicos do Sistema Nervoso Central');
INSERT INTO doenca  (ref,designacao) VALUES (82, 'Raiva');
INSERT INTO doenca  (ref,designacao) VALUES (83, 'Encefalite Por Vírus Transmitidos Por Mosquitos');
INSERT INTO doenca  (ref,designacao) VALUES (84, 'Encefalite Por Vírus Transmitido Por Carrapatos');
INSERT INTO doenca  (ref,designacao) VALUES (85, 'Outras Encefalites Virais, Não Classificadas em Outra Parte');
INSERT INTO doenca  (ref,designacao) VALUES (86, 'Encefalite Viral, Não Especificada');
INSERT INTO doenca  (ref,designacao) VALUES (87, 'Meningite Viral');
INSERT INTO doenca  (ref,designacao) VALUES (88, 'Outras Infecções Virais do Sistema Nervoso Central Não Classificadas em Outra Parte');
INSERT INTO doenca  (ref,designacao) VALUES (89, 'Infecções Virais Não Especificadas do Sistema Nervoso Central');
INSERT INTO doenca  (ref,designacao) VALUES (90, 'Dengue (dengue Clássico)');
INSERT INTO doenca  (ref,designacao) VALUES (91, 'Febre Hemorrágica Devida ao Vírus do Dengue');
INSERT INTO doenca  (ref,designacao) VALUES (92, 'Outras Febres Virais Transmitidas Por Mosquitos');
INSERT INTO doenca  (ref,designacao) VALUES (93, 'Outras Febres Por Vírus Transmitidas Por Artrópodes Não Classificadas em Outra Parte');
INSERT INTO doenca  (ref,designacao) VALUES (94, 'Febre Viral Transmitida Por Artrópodes, Não Especificada');
INSERT INTO doenca  (ref,designacao) VALUES (95, 'Febre Amarela');
INSERT INTO doenca  (ref,designacao) VALUES (96, 'Febre Hemorrágica Por Arenavírus');
INSERT INTO doenca  (ref,designacao) VALUES (98, 'Outras Febres Hemorrágicas Por Vírus, Não Classificadas em Outra Parte');
INSERT INTO doenca  (ref,designacao) VALUES (99, 'Febres Hemorrágicas Virais Não Especificadas');
INSERT INTO doenca(ref, designacao) VALUES (100,'Anencefalia e Malformações Similares');
INSERT INTO doenca(ref, designacao) VALUES (101,'Encefalocele');
INSERT INTO doenca(ref, designacao) VALUES (102,'Microcefalia');
INSERT INTO doenca(ref, designacao) VALUES (103,'Hidrocefalia Congênita');
INSERT INTO doenca(ref, designacao) VALUES (104,'Outras Malformações Congênitas do Cérebro');
INSERT INTO doenca(ref, designacao) VALUES (105,'Espinha Bífida');
INSERT INTO doenca(ref, designacao) VALUES (106,'Outras Malformações Congênitas da Medula Espinhal');
INSERT INTO doenca(ref, designacao) VALUES (107,'Outras Malformações Congênitas do Sistema Nervoso');
INSERT INTO doenca(ref, designacao) VALUES (110,'Malformações Congênitas Das Pálpebras, do Aparelho Lacrimal e da Órbita');
INSERT INTO doenca(ref, designacao) VALUES (111,'Anoftalmia, Microftalmia e Macroftalmia');
INSERT INTO doenca(ref, designacao) VALUES (112,'Malformações Congênitas do Cristalino');
INSERT INTO doenca(ref, designacao) VALUES (113,'Malformações Congênitas da Câmara Anterior do Olho');
INSERT INTO doenca(ref, designacao) VALUES (114,'Malformações Congênitas da Câmara Posterior do Olho');
INSERT INTO doenca(ref, designacao) VALUES (115,'Outras Malformações Congênitas do Olho');
INSERT INTO doenca(ref, designacao) VALUES (116,'Malformações Congênitas do Ouvido Causando Comprometimento da Audição');
INSERT INTO doenca(ref, designacao) VALUES (117,'Outras Malformações Congênitas da Orelha');
INSERT INTO doenca(ref, designacao) VALUES (118,'Outras Malformações Congênitas da Face e do Pescoço');
INSERT INTO doenca(ref, designacao) VALUES (120,'Malformações Congênitas Das Câmaras e Das Comunicações Cardíacas');
INSERT INTO doenca(ref, designacao) VALUES (121,'Malformações Congênitas Dos Septos Cardíacos');
INSERT INTO doenca(ref, designacao) VALUES (122,'Malformações Congênitas Das Valvas Pulmonar e Tricúspide');
INSERT INTO doenca(ref, designacao) VALUES (123,'Malformações Congênitas Das Valvas Aórtica e Mitral');
INSERT INTO doenca(ref, designacao) VALUES (124,'Outras Malformações Congênitas do Coração');
INSERT INTO doenca(ref, designacao) VALUES (125,'Malformações Congênitas Das Grandes Artérias');
INSERT INTO doenca(ref, designacao) VALUES (126,'Malformações Congênitas Das Grandes Veias');
INSERT INTO doenca(ref, designacao) VALUES (127,'Outras Malformações Congênitas do Sistema Vascular Periférico');
INSERT INTO doenca(ref, designacao) VALUES (128,'Outras Malformações Congênitas do Aparelho Circulatório');
INSERT INTO doenca(ref, designacao) VALUES (130,'Malformação Congênita do Nariz');
INSERT INTO doenca(ref, designacao) VALUES (131,'Malformações Congênitas da Laringe');
INSERT INTO doenca(ref, designacao) VALUES (132,'Malformações Congênitas da Traquéia e Dos Brônquios');
INSERT INTO doenca(ref, designacao) VALUES (133,'Malformações Congênitas do Pulmão');
INSERT INTO doenca(ref, designacao) VALUES (134,'Outras Malformações Congênitas do Aparelho Respiratório');
INSERT INTO doenca(ref, designacao) VALUES (135,'Fenda Palatina');
INSERT INTO doenca(ref, designacao) VALUES (136,'Fenda Labial');
INSERT INTO doenca(ref, designacao) VALUES (137,'Fenda Labial Com Fenda Palatina');
INSERT INTO doenca(ref, designacao) VALUES (138,'Outras Malformações Congênitas da Língua, da Boca e da Faringe');
INSERT INTO doenca(ref, designacao) VALUES (139,'Malformações Congênitas do Esôfago');
INSERT INTO doenca(ref, designacao) VALUES (140,'Outras Malformações Congênitas do Trato Digestivo Superior');
INSERT INTO doenca(ref, designacao) VALUES (141,'Ausência, Atresia e Estenose Congênita do Intestino Delgado');
INSERT INTO doenca(ref, designacao) VALUES (142,'Ausência, Atresia e Estenose Congênita do Cólon');
INSERT INTO doenca(ref, designacao) VALUES (143,'Outras Malformações Congênitas do Intestino');
INSERT INTO doenca(ref, designacao) VALUES (144,'Malformações Congênitas da Vesícula Biliar, Das Vias Biliares e do Fígado');
INSERT INTO doenca(ref, designacao) VALUES (145,'Outras Malformações Congênitas do Aparelho Digestivo');
INSERT INTO doenca(ref, designacao) VALUES (150,'Malformações Congênitas Dos Ovários, Das Trompas de Falópio e Dos Ligamentos Largos');
INSERT INTO doenca(ref, designacao) VALUES (151,'Malformações Congênitas do Útero e do Colo do Útero');
INSERT INTO doenca(ref, designacao) VALUES (152,'Outras Malformações Congênitas Dos Órgãos Genitais Femininos');
INSERT INTO doenca(ref, designacao) VALUES (153,'Testículo Não-descido');
INSERT INTO doenca(ref, designacao) VALUES (154,'Hipospádias');
INSERT INTO doenca(ref, designacao) VALUES (155,'Outras Malformações Congênitas Dos Órgãos Genitais Masculinos');
INSERT INTO doenca(ref, designacao) VALUES (156,'Sexo Indeterminado e Pseudo-hermafroditismo');
INSERT INTO doenca(ref, designacao) VALUES (160,'Agenesia Renal e Outros Defeitos de Redução do Rim');
INSERT INTO doenca(ref, designacao) VALUES (161,'Doenças Císticas do Rim');
INSERT INTO doenca(ref, designacao) VALUES (162,'Anomalias Congênitas Obstrutivas da Pelve Renal e Malformações Congênitas do Ureter');
INSERT INTO doenca(ref, designacao) VALUES (163,'Outras Malformações Congênitas do Rim');
INSERT INTO doenca(ref, designacao) VALUES (164,'Outras Malformações Congênitas do Aparelho Urinário');
INSERT INTO doenca(ref, designacao) VALUES (165,'Malformações Congênitas do1uadril');
INSERT INTO doenca(ref, designacao) VALUES (166,'Deformidades Congênitas do pé');
INSERT INTO doenca(ref, designacao) VALUES (167,'Deformidades Osteomusculares Congênitas da Cabeça, da Face, da Coluna e do Tórax');
INSERT INTO doenca(ref, designacao) VALUES (168,'Outras Deformidades Osteomusculares Congênitas');
INSERT INTO doenca(ref, designacao) VALUES (169,'Polidactilia');
INSERT INTO doenca(ref, designacao) VALUES (170,'Sindactilia');
INSERT INTO doenca(ref, designacao) VALUES (171,'Defeitos, Por Redução, do Membro Superior');
INSERT INTO doenca(ref, designacao) VALUES (172,'Defeitos, Por Redução, do Membro Inferior');
INSERT INTO doenca(ref, designacao) VALUES (173,'Defeitos Por Redução de Membro Não Especificado');
INSERT INTO doenca(ref, designacao) VALUES (174,'Outras Malformações Congênitas Dos Membros');
INSERT INTO doenca(ref, designacao) VALUES (175,'Outras Malformações Congênitas Dos Ossos do Crânio e da Face');
INSERT INTO doenca(ref, designacao) VALUES (176,'Malformações Congênitas da Coluna Vertebral e Dos Ossos do Tórax');
INSERT INTO doenca(ref, designacao) VALUES (177,'Osteocondrodisplasia Com Anomalias de Crescimento Dos Ossos Longos e da Coluna Vertebral');
INSERT INTO doenca(ref, designacao) VALUES (178,'Outras Osteocondrodisplasias');
INSERT INTO doenca(ref, designacao) VALUES (179,'Malformações Congênitas do Sistema Osteomuscular Não Classificadas em Outra Parte');
INSERT INTO doenca(ref, designacao) VALUES (180,'Ictiose Congênita');
INSERT INTO doenca(ref, designacao) VALUES (181,'Epidermólise Bolhosa');
INSERT INTO doenca(ref, designacao) VALUES (182,'Outras Malformações Congênitas da Pele');
INSERT INTO doenca(ref, designacao) VALUES (183,'Malformações Congênitas da Mama');
INSERT INTO doenca(ref, designacao) VALUES (184,'Outras Malformações Congênitas do Tegumento');
INSERT INTO doenca(ref, designacao) VALUES (185,'Facomatoses Não Classificadas em Outra Parte');
INSERT INTO doenca(ref, designacao) VALUES (186,'Síndromes Com Malformações Congênitas Devidas a Causas Exógenas Conhecidas, Não Classificadas em Outra Parte');
INSERT INTO doenca(ref, designacao) VALUES (187,'Outras Síndromes Com Malformações Congênitas1ue Acometem Múltiplos Sistemas');
INSERT INTO doenca(ref, designacao) VALUES (189,'Outras Malformações Congênitas Não Classificadas em Outra Parte');
INSERT INTO doenca(ref, designacao) VALUES (190,'Síndrome de Down');
INSERT INTO doenca(ref, designacao) VALUES (191,'Síndrome de Edwards e Síndrome de Patau');
INSERT INTO doenca(ref, designacao) VALUES (192,'Outras Trissomias e Trissomias Parciais Dos Autossomos, Não Classificadas em Outra Parte');
INSERT INTO doenca(ref, designacao) VALUES (193,'Monossomias e Deleções Dos Autossomos, Não Classificadas em Outra Parte');
INSERT INTO doenca(ref, designacao) VALUES (195,'Rearranjos Equilibrados e Marcadores Estruturais, Não Classificados em Outra Parte');
INSERT INTO doenca(ref, designacao) VALUES (196,'Síndrome de Turner');
INSERT INTO doenca(ref, designacao) VALUES (197,'Outras Anomalias Dos Cromossomos Sexuais, Fenótipo Feminino, Não Classificadas em Outra Parte');
INSERT INTO doenca(ref, designacao) VALUES (198,'Outras Anomalias Dos Cromossomos Sexuais, Fenótipo Masculino, Não Classificadas em Outra Parte');
INSERT INTO doenca(ref, designacao) VALUES (199,'Outras Anomalias Dos Cromossomos, Não Classificadas em Outra Parte');
INSERT INTO doenca(ref, designacao) VALUES (200,'Traumatismos Superficiais Envolvendo Múltiplas Regiões do Corpo');
INSERT INTO doenca(ref, designacao) VALUES (201,'Ferimentos Envolvendo Múltiplas Regiões do Corpo');
INSERT INTO doenca(ref, designacao) VALUES (202,'Fraturas Envolvendo Múltiplas Regiões do Corpo');
INSERT INTO doenca(ref, designacao) VALUES (203,'Luxações, Entorses e Distensões Envolvendo Regiões Múltiplas do Corpo');
INSERT INTO doenca(ref, designacao) VALUES (204,'Traumatismos Por Esmagamento Envolvendo Múltiplas Regiões do Corpo');
INSERT INTO doenca(ref, designacao) VALUES (205,'Amputações Traumáticas Envolvendo Múltiplas Regiões do Corpo');
INSERT INTO doenca(ref, designacao) VALUES (206,'Outros Traumatismos Envolvendo Regiões Múltiplas do Corpo, Não Classificados em Outra Parte');
INSERT INTO doenca(ref, designacao) VALUES (207,'Traumatismos Múltiplos Não Especificados');
INSERT INTO doenca(ref, designacao) VALUES (208,'Fratura da Coluna, Nível Não Especificado');
INSERT INTO doenca(ref, designacao) VALUES (209,'Outros Traumatismos de Coluna e Tronco, Nível Não Especificado');
INSERT INTO doenca(ref, designacao) VALUES (210,'Fratura do Membro Superior, Nível Não Especificado');
INSERT INTO doenca(ref, designacao) VALUES (211,'Outros Traumatismos de Membro Superior, Nível Não Especificado');
INSERT INTO doenca(ref, designacao) VALUES (212,'Fratura do Membro Inferior, Nível Não Especificado');
INSERT INTO doenca(ref, designacao) VALUES (213,'Outros Traumatismos de Membro Inferior, Nível Não Especificado');
INSERT INTO doenca(ref, designacao) VALUES (214,'Traumatismo de Região Não Especificada do Corpo');
INSERT INTO doenca(ref, designacao) VALUES (215,'Corpo Estranho na Parte Externa do Olho');
INSERT INTO doenca(ref, designacao) VALUES (216,'Corpo Estranho no Ouvido');
INSERT INTO doenca(ref, designacao) VALUES (217,'Corpo Estranho no Trato Respiratório');
INSERT INTO doenca(ref, designacao) VALUES (218,'Corpo Estranho no Aparelho Digestivo');
INSERT INTO doenca(ref, designacao) VALUES (219,'Corpo Estranho no Trato Geniturinário');
INSERT INTO doenca(ref, designacao) VALUES (220,'Queimadura e Corrosão da Cabeça e Pescoço');
INSERT INTO doenca(ref, designacao) VALUES (221,'Queimadura e Corrosão do Tronco');
INSERT INTO doenca(ref, designacao) VALUES (222,'Queimadura e Corrosão do Ombro e Membro Superior, Exceto Punho e Mão');
INSERT INTO doenca(ref, designacao) VALUES (223,'Queimadura e Corrosão do Punho e da Mão');
INSERT INTO doenca(ref, designacao) VALUES (224,'Queimadura e Corrosão do Quadril e Membro Inferior, Exceto Tornozelo e do pé');
INSERT INTO doenca(ref, designacao) VALUES (225,'Queimadura e Corrosão do Tornozelo e do pé');
INSERT INTO doenca(ref, designacao) VALUES (226,'Queimadura e Corrosão Limitadas ao Olho e Seus Anexos');
INSERT INTO doenca(ref, designacao) VALUES (227,'Queimadura e Corrosão do Trato Respiratório');
INSERT INTO doenca(ref, designacao) VALUES (228,'Queimadura e Corrosão de Outros Órgãos Internos');
INSERT INTO doenca(ref, designacao) VALUES (229,'Queimaduras e Corrosões de Múltiplas Regiões do Corpo');
INSERT INTO doenca(ref, designacao) VALUES (230,'Queimadura e Corrosão, Parte Não Especificada do Corpo');
INSERT INTO doenca(ref, designacao) VALUES (231,'Queimaduras Classificadas Segundo a Extensão da Superfície Corporal Atingida');
INSERT INTO doenca(ref, designacao) VALUES (232,'Corrosões Classificadas Segundo a Extensão da Superfície Corporal Atingida');
INSERT INTO doenca(ref, designacao) VALUES (233,'Geladura Superficial');
INSERT INTO doenca(ref, designacao) VALUES (234,'Geladura Com Necrose de Tecidos');
INSERT INTO doenca(ref, designacao) VALUES (235,'Geladura de Múltiplas Partes do Corpo e Das Não Especificadas');
INSERT INTO doenca(ref, designacao) VALUES (236,'Intoxicação Por Antibióticos Sistêmicos');
INSERT INTO doenca(ref, designacao) VALUES (237,'Intoxicação Por Outras Substâncias Antiinfecciosas ou Antiparasitárias Sistêmicas');
INSERT INTO doenca(ref, designacao) VALUES (238,'Intoxicação Por Hormônios, Seus Substitutos Sintéticos e Seus Antagonistas Não Classificados em Outra Parte');
INSERT INTO doenca(ref, designacao) VALUES (239,'Intoxicação Por Analgésicos, Antipiréticos e Anti-reumáticos Não-opiáceos');
INSERT INTO doenca(ref, designacao) VALUES (240,'Intoxicação Por Narcóticos e Psicodislépticos (alucinógenos)');
INSERT INTO doenca(ref, designacao) VALUES (241,'Intoxicação Por Anestésicos e Gases Terapêuticos');
INSERT INTO doenca(ref, designacao) VALUES (242,'Intoxicação Por Antiepilépticos, Sedativos-hipnóticos e Antiparkinsonianos');
INSERT INTO doenca(ref, designacao) VALUES (243,'Intoxicação Por Drogas Psicotrópicas Não Classificadas em Outra Parte');
INSERT INTO doenca(ref, designacao) VALUES (244,'Intoxicação Por Drogas Que Afetam Principalmente o Sistema Nervoso Autônomo');
INSERT INTO doenca(ref, designacao) VALUES (245,'Intoxicação Por Substâncias de Ação Essencialmente Sistêmica e Substâncias Hematológicas, Não Classificadas em Outra Parte');
INSERT INTO doenca(ref, designacao) VALUES (246,'Intoxicação Por Substâncias Que Atuam Primariamente Sobre o Aparelho Circulatório');
INSERT INTO doenca(ref, designacao) VALUES (247,'Intoxicação Por Substâncias Que Atuam Primariamente Sobre o Aparelho Gastrointestinal');
INSERT INTO doenca(ref, designacao) VALUES (248,'Intoxicação Por Substâncias Que Atuam Primariamente Sobre os Músculos Lisos e Esqueléticos e Sobre o Aparelho Respiratório');
INSERT INTO doenca(ref, designacao) VALUES (249,'Intoxicação Por Substâncias de Uso Tópico Que Atuam Primariamente Sobre a Pele e as Mucosas e Por Medicamentos Utilizados em Oftalmologia, Otorrinolaringologia e Odontologia');
INSERT INTO doenca(ref, designacao) VALUES (250,'Intoxicação Por Diuréticos e Outras Drogas, Medicamentos e Substâncias Biológicas e as Não Especificadas');
INSERT INTO doenca(ref, designacao) VALUES (251,'Efeito Tóxico do Álcool');
INSERT INTO doenca(ref, designacao) VALUES (252,'Efeito Tóxico de Solventes Orgânicos');
INSERT INTO doenca(ref, designacao) VALUES (253,'Efeito Tóxico de Derivados Halogênicos de Hidrocarbonetos Alifáticos e Aromáticos');
INSERT INTO doenca(ref, designacao) VALUES (254,'Efeito Tóxico de Corrosivos');
INSERT INTO doenca(ref, designacao) VALUES (255,'Efeito Tóxico de Sabões e Detergentes');
INSERT INTO doenca(ref, designacao) VALUES (256,'Efeito Tóxico de Metais');
INSERT INTO doenca(ref, designacao) VALUES (257,'Efeito Tóxico de Outras Substâncias Inorgânicas');
INSERT INTO doenca(ref, designacao) VALUES (258,'Efeito Tóxico do Monóxido de Carbono');
INSERT INTO doenca(ref, designacao) VALUES (259,'Efeito Tóxico de Outros Gases, Fumaças e Vapores');
INSERT INTO doenca(ref, designacao) VALUES (260,'Efeito Tóxico de Pesticidas');
INSERT INTO doenca(ref, designacao) VALUES (261,'Efeito Tóxico de Substâncias Nocivas Consumidas Como Fruto do Mar');
INSERT INTO doenca(ref, designacao) VALUES (262,'Efeito Tóxico de Outras Substâncias Nocivas Ingeridas Como Alimento');
INSERT INTO doenca(ref, designacao) VALUES (263,'Efeito Tóxico de Contato Com Animais Venenosos');
INSERT INTO doenca(ref, designacao) VALUES (264,'Efeito Tóxico da Aflatoxina e de Outras Micotoxinas Contaminantes de Alimentos');
INSERT INTO doenca(ref, designacao) VALUES (265,'Efeito Tóxico de Outras Substâncias e as Não Especificadas');
INSERT INTO doenca(ref, designacao) VALUES (266,'Efeitos Não Especificados de Radiação');
INSERT INTO doenca(ref, designacao) VALUES (267,'Efeitos do Calor e da Luz');
INSERT INTO doenca(ref, designacao) VALUES (268,'Hipotermia');
INSERT INTO doenca(ref, designacao) VALUES (269,'Outros Efeitos da Temperatura Reduzida');
INSERT INTO doenca(ref, designacao) VALUES (270,'Efeitos da Pressão Atmosférica e da Pressão da Água');
INSERT INTO doenca(ref, designacao) VALUES (271,'Asfixia');
INSERT INTO doenca(ref, designacao) VALUES (273,'Efeitos de Outras Privações');
INSERT INTO doenca(ref, designacao) VALUES (274,'Síndromes de Maus Tratos');
INSERT INTO doenca(ref, designacao) VALUES (275,'Efeitos de Outras Causas Externas');
INSERT INTO doenca(ref, designacao) VALUES (278,'Efeitos Adversos Não Classificados em Outra Parte');
INSERT INTO doenca(ref, designacao) VALUES (279,'Algumas Complicações Precoces Dos Traumatismos Não Classificadas em Outra Parte');
INSERT INTO doenca(ref, designacao) VALUES (280,'Complicações Conseqüentes à Infusão, Transfusão ou Injeção Terapêutica');
INSERT INTO doenca(ref, designacao) VALUES (281,'Complicações de Procedimentos Não Classificadas em Outra Parte');
INSERT INTO doenca(ref, designacao) VALUES (282,'Complicações de Dispositivos Protéticos, Implantes e Enxertos Cardíacos e Vasculares');
INSERT INTO doenca(ref, designacao) VALUES (283,'Complicações de Dispositivos Protéticos, Implantes e Enxertos Geniturinários Internos');
INSERT INTO doenca(ref, designacao) VALUES (284,'Complicações de Dispositivos Protéticos, Implantes e Enxertos Ortopédicos Internos');
INSERT INTO doenca(ref, designacao) VALUES (285,'Complicações de Outros Dispositivos Protéticos, Implantes e Enxertos Internos');
INSERT INTO doenca(ref, designacao) VALUES (286,'Falha e Rejeição de Órgãos e Tecidos Transplantados');
INSERT INTO doenca(ref, designacao) VALUES (287,'Complicações Próprias de Reimplante e Amputação');
INSERT INTO doenca(ref, designacao) VALUES (288,'Outras Complicações de Cuidados Médicos e Cirúrgicos Não Classificadas em Outra Parte');
INSERT INTO doenca(ref, designacao) VALUES (290,'Seqüelas de Traumatismo da Cabeça');
INSERT INTO doenca(ref, designacao) VALUES (291,'Seqüelas de Traumatismos do Pescoço e do Tronco');
INSERT INTO doenca(ref, designacao) VALUES (292,'Seqüelas de Traumatismos do Membro Superior');
INSERT INTO doenca(ref, designacao) VALUES (293,'Seqüelas de Traumatismos do Membro Inferior');
INSERT INTO doenca(ref, designacao) VALUES (294,'Seqüelas de Traumatismos Envolvendo Múltiplas Regiões do Corpo e as Não Especificadas');
INSERT INTO doenca(ref, designacao) VALUES (295,'Seqüelas de Queimaduras, Corrosões e Geladuras');
INSERT INTO doenca(ref, designacao) VALUES (296,'Seqüelas de Intoxicação Por Drogas, Medicamentos e Substâncias Biológicas');
INSERT INTO doenca(ref, designacao) VALUES (297,'Seqüelas de Efeitos Tóxicos de Substâncias de Origem Predominantemente Não-medicinal');
INSERT INTO doenca(ref, designacao) VALUES (298,'Seqüelas de Outros Efeitos de Causas Externas e Dos Não Especificados');
